import type { Metadata } from "next";
import Sidebar from "@/components/ui/sidebar";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Interactive | Kepler-16b",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-50 min-h-screen text-slate-900 antialiased">
        {children}
      </body>
    </html>
  );
}
